[package]
name = "bcs_stream"
version = "0.0.0"

[addresses]
bcs_stream = "0xCAFE"

[dependencies]
TopoStdlib = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "topo-stdlib", rev = "mainnet" }
