[package]
name = "Pyth"
version = "0.0.1"

[dependencies]
TopoFramework = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }

[addresses]
pyth = "_"
