[package]
name = "calculator"
version = "0.0.0"

[addresses]
account = "_"

[dependencies]
TopoFramework = { local = "../../../framework/topo-framework" }
AptosStdlib = { local = "../../../framework/aptos-stdlib" }
