[package]
name = "fixed_point64"
version = "1.0.0"
authors = []

[addresses]
fixed_point64 = "0xdeadbeef"

[dev-addresses]

[dependencies.TopoFramework]
git = "https://github.com/Topo-Labs/topo_framework.git"
rev = "mainnet"
subdir = "topo-framework"

[dev-dependencies]
