[package]
name = "CommonAccount"
version = "1.0.0"

[dependencies]
TopoFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "topo-framework", rev = "mainnet" }

[addresses]
common_account = "_"
