[package]
name = "ManagedFungibleAsset"
version = "0.0.0"

[addresses]
topo_framework = "0x1"
topo_token_objects = "0x4"
example_addr = "_"

[dependencies]
TopoFramework = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
TopoTokenObjects = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-token-objects", rev = "mainnet" }
