[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"
topo_framework = "0x1"

[dependencies]
TopoFramework = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
TopoToken = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-token", rev = "mainnet" }
