[package]
name = "raffle"
version = "0.0.1"

[dependencies]
TopoFramework = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "aptos-stdlib", rev = "mainnet" }


[addresses]
raffle = "_"