[package]
name = "raffle"
version = "0.0.1"

[dependencies]
TopoFramework = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
TopoStdlib = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-stdlib", rev = "mainnet" }


[addresses]
raffle = "_"