[package]
name = "Examples"
version = "0.0.0"

[addresses]
DogCoin = "0x2"

[dependencies]
TopoFramework = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
