[package]
name = "empty"
version = "1.0.0"
authors = []

[addresses]
empty = "0xcafe"

[dev-addresses]

[dependencies.TopoFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "topo-framework"

[dev-dependencies]
