[package]
name = "Examples"
version = "0.0.0"

[addresses]
defi = "_"

[dependencies]
TopoFramework = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
