[package]
name = "Hero"
version = "0.0.0"

[addresses]
hero = "_"

[dependencies]
TopoFramework = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
TopoTokenObjects = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-token-objects", rev = "mainnet" }
