[package]
name = "MessageBoard"
version = "0.0.1"

[dependencies]
TopoFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "topo-framework", rev = "mainnet" }

[addresses]
std = "0x1"
message_board = "_"
