[package]
name = "TopoTokenObjects"
version = "1.0.0"

[addresses]
std = "0x1"
topo_std = "0x1"
topo_framework = "0x1"
topo_token_objects = "0x4"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
TopoFramework = { local = "../topo-framework"}
