[package]
name = "Explorer"
version = "1.0.0"
authors = []
upgrade_policy = "immutable"

[addresses]
explorer = "0x7f1bb834cc9495a6fccd689478ed22b5c46ff2a0eb2ddda842f4f31f83778191"

[dev-addresses]
explorer = "0x123"

[dependencies]
TopoFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/topo-framework" }
TopoStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/topo-stdlib" }