[package]
name = 'tic-tac-toe'
version = '1.0.0'

[addresses]
tic_tac_toe = "_"

[dependencies]
TopoFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "topo-framework", rev = "mainnet" }
