[package]
name = "cli_e2e_tests"
version = "0.0.1"

[addresses]
addr = "_"

[dev-addresses]
addr = "0x12345"

[dependencies.TopoFramework]
git = "https://github.com/Topo-Labs/topo_framework.git"
rev = "mainnet"
subdir = "topo-framework"

[dependencies.TopoTokenObjects]
git = "https://github.com/Topo-Labs/topo_framework.git"
rev = "mainnet"
subdir = "topo-token-objects"
