[package]
name = "CliArgs"
version = "0.1.0"
upgrade_policy = "compatible"

[addresses]
test_account = "_"

[dependencies.TopoFramework]
git = "https://github.com/tuminfei/topo_framework.git"
subdir = "topo-framework"
rev = "mainnet"