[package]
name = 'guild'
version = '1.0.0'

[addresses]
guild = "_"

[dependencies]
TopoFramework = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
TopoTokenObjects = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-token-objects", rev = "mainnet" }
