[package]
name = 'token_lockup'
version = '1.0.0'

[addresses]
token_lockup = "_"

[dependencies]
TopoFramework = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
TopoTokenObjects = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "topo-token-objects", rev = "mainnet" }
