[package]
name = "TooLargeTest"
version = "0.0.0"

[dependencies]
TopoFramework = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "move-stdlib", rev = "mainnet" }
