[package]
name = "PocFramework"
version = "0.0.0"

[addresses]
poc_framework = "bfe262acf85005487af8911dc00d3587178c26bd0ff5443a89614da5f823028d"

[dependencies]
TopoFramework = { local = "../../framework/topo-framework" }
