[package]
name = "basic_coin"
version = "0.0.0"

[addresses]
named_addr = "0xCAFE"

[dependencies.TopoStdlib]
git = 'https://github.com/tuminfei/topo_framework.git'
rev = 'main'
subdir = 'topo-stdlib'
