[package]
name = "OnChainDice"
version = "0.0.0"

[addresses]
module_owner = "_"

[dependencies]
TopoFramework = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
