[package]
name = "OnChainDice"
version = "0.0.0"

[addresses]
module_owner = "_"

[dependencies]
TopoFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "topo-framework", rev = "mainnet" }
