[package]
name = "LargePackageExample"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
TopoFramework = { git = "https://github.com/Topo-Labs/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }

[addresses]
large_package_example = "_"
