[package]
name = "MyCoins"
version = "0.0.0"

[addresses]
MyCoins = "0x2"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
