[package]
name = "aggregator_examples"
version = "0.0.0"

[addresses]
aggregator_examples = "0xCAFE"

[dependencies]
AptosStdlib = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "aptos-stdlib", rev = "mainnet" }
TopoFramework = { git = "https://github.com/tuminfei/topo_framework.git", subdir = "topo-framework", rev = "mainnet" }
