///
/// TopoGovernance represents the on-chain governance of the Aptos network. Voting power is calculated based on the
/// current effective power of the proposer or voter in `staking_registry`.
///
/// It provides the following flow:
/// 1. Proposers can create a proposal by calling TopoGovernance::create_proposal. The proposer's backing stake pool
/// needs to have the minimum proposer stake required. Off-chain components can subscribe to CreateProposalEvent to
/// track proposal creation and proposal ids.
/// 2. Voters can vote on a proposal. Their voting power is derived from the backing stake pool. A stake pool can vote
/// on a proposal multiple times as long as the total voting power of these votes doesn't exceed its total voting power.
module topo_framework::topo_governance {
    use std::error;
    use std::option;
    use std::signer;
    use std::string::{Self, String, utf8};
    use std::features;

    use aptos_std::math64::min;
    use aptos_std::simple_map::{Self, SimpleMap};
    use aptos_std::smart_table::{Self, SmartTable};
    use aptos_std::table::{Self, Table};

    use topo_framework::account::{Self, SignerCapability, create_signer_with_capability};
    use topo_framework::poc_power_store;
    use topo_framework::event::{Self, EventHandle};
    use topo_framework::governance_proposal::{Self, GovernanceProposal};
    use topo_framework::stake;
    use topo_framework::staking_registry;
    use topo_framework::staking_config;
    use topo_framework::system_addresses;
    use topo_framework::topo_coin;
    use topo_framework::chunky_dkg_config;
    use topo_framework::consensus_config;
    use topo_framework::permissioned_signer;
    use topo_framework::randomness_config;
    use topo_framework::reconfiguration_with_dkg;
    use topo_framework::timestamp;
    use topo_framework::voting;

    #[test_only]
    use std::vector;

    /// The specified stake pool does not have sufficient stake to create a proposal
    const EINSUFFICIENT_PROPOSER_STAKE: u64 = 1;
    /// The specified stake pool must be part of the validator set
    const ENO_VOTING_POWER: u64 = 5;
    /// Proposal is not ready to be resolved. Waiting on time or votes
    const EPROPOSAL_NOT_RESOLVABLE_YET: u64 = 6;
    /// The proposal has not been resolved yet
    const EPROPOSAL_NOT_RESOLVED_YET: u64 = 8;
    /// Metadata location cannot be longer than 256 chars
    const EMETADATA_LOCATION_TOO_LONG: u64 = 9;
    /// Metadata hash cannot be longer than 256 chars
    const EMETADATA_HASH_TOO_LONG: u64 = 10;
    /// Account is not authorized to call this function.
    const EUNAUTHORIZED: u64 = 11;
    /// The stake pool is using voting power more than it has.
    const EVOTING_POWER_OVERFLOW: u64 = 12;
    /// Partial voting feature hasn't been properly initialized.
    const EPARTIAL_VOTING_NOT_INITIALIZED: u64 = 13;
    /// The proposal in the argument is not a partial voting proposal.
    const ENOT_PARTIAL_VOTING_PROPOSAL: u64 = 14;
    /// The proposal has expired.
    const EPROPOSAL_EXPIRED: u64 = 15;
    /// Current permissioned signer cannot perform governance operations.
    const ENO_GOVERNANCE_PERMISSION: u64 = 16;

    /// This matches the same enum const in voting. We have to duplicate it as Move doesn't have support for enums yet.
    const PROPOSAL_STATE_SUCCEEDED: u64 = 1;

    const MAX_U64: u64 = 18446744073709551615;

    /// Proposal metadata attribute keys.
    const METADATA_LOCATION_KEY: vector<u8> = b"metadata_location";
    const METADATA_HASH_KEY: vector<u8> = b"metadata_hash";

    /// Store the SignerCapabilities of accounts under the on-chain governance's control.
    struct GovernanceResponsbility has key {
        signer_caps: SimpleMap<address, SignerCapability>,
    }

    /// Configurations of the TopoGovernance, set during Genesis and can be updated by the same process offered
    /// by this TopoGovernance module.
    struct GovernanceConfig has key {
        min_voting_threshold: u128,
        required_proposer_stake: u64,
        voting_duration_secs: u64,
    }

    struct RecordKey has copy, drop, store {
        voter: address,
        proposal_id: u64,
    }

    /// Records to track the proposals each stake pool has been used to vote on.
    struct VotingRecords has key {
        votes: Table<RecordKey, bool>
    }

    /// Records to track the voting power usage of each stake pool on each proposal.
    struct VotingRecordsV2 has key {
        votes: SmartTable<RecordKey, u64>
    }

    /// Used to track which execution script hashes have been approved by governance.
    /// This is required to bypass cases where the execution scripts exceed the size limit imposed by mempool.
    struct ApprovedExecutionHashes has key {
        hashes: SimpleMap<u64, vector<u8>>,
    }

    /// Events generated by interactions with the TopoGovernance module.
    struct GovernanceEvents has key {
        create_proposal_events: EventHandle<CreateProposalEvent>,
        update_config_events: EventHandle<UpdateConfigEvent>,
        vote_events: EventHandle<VoteEvent>,
    }

    /// Event emitted when a proposal is created.
    struct CreateProposalEvent has drop, store {
        proposer: address,
        proposal_id: u64,
        execution_hash: vector<u8>,
        proposal_metadata: SimpleMap<String, vector<u8>>,
    }

    /// Event emitted when there's a vote on a proposa;
    struct VoteEvent has drop, store {
        proposal_id: u64,
        voter: address,
        num_votes: u64,
        should_pass: bool,
    }

    /// Event emitted when the governance configs are updated.
    struct UpdateConfigEvent has drop, store {
        min_voting_threshold: u128,
        required_proposer_stake: u64,
        voting_duration_secs: u64,
    }

    #[event]
    /// Event emitted when a proposal is created.
    struct CreateProposal has drop, store {
        proposer: address,
        proposal_id: u64,
        execution_hash: vector<u8>,
        proposal_metadata: SimpleMap<String, vector<u8>>,
    }

    #[event]
    /// Event emitted when there's a vote on a proposa;
    struct Vote has drop, store {
        proposal_id: u64,
        voter: address,
        num_votes: u64,
        should_pass: bool,
    }

    #[event]
    /// Event emitted when the governance configs are updated.
    struct UpdateConfig has drop, store {
        min_voting_threshold: u128,
        required_proposer_stake: u64,
        voting_duration_secs: u64,
    }

    struct GovernancePermission has copy, drop, store {}

    /// Permissions
    inline fun check_governance_permission(s: &signer) {
        assert!(
            permissioned_signer::check_permission_exists(s, GovernancePermission {}),
            error::permission_denied(ENO_GOVERNANCE_PERMISSION),
        );
    }

    /// Grant permission to perform governance operations on behalf of the master signer.
    public fun grant_permission(master: &signer, permissioned_signer: &signer) {
        permissioned_signer::authorize_unlimited(master, permissioned_signer, GovernancePermission {})
    }

    /// Can be called during genesis or by the governance itself.
    /// Stores the signer capability for a given address.
    public fun store_signer_cap(
        topo_framework: &signer,
        signer_address: address,
        signer_cap: SignerCapability,
    ) acquires GovernanceResponsbility {
        system_addresses::assert_aptos_framework(topo_framework);
        system_addresses::assert_framework_reserved(signer_address);

        if (!exists<GovernanceResponsbility>(@topo_framework)) {
            move_to(
                topo_framework,
                GovernanceResponsbility { signer_caps: simple_map::create<address, SignerCapability>() }
            );
        };

        let signer_caps = &mut borrow_global_mut<GovernanceResponsbility>(@topo_framework).signer_caps;
        signer_caps.add(signer_address, signer_cap);
    }

    /// Initializes the state for Aptos Governance. Can only be called during Genesis with a signer
    /// for the topo_framework (0x1) account.
    /// This function is private because it's called directly from the vm.
    fun initialize(
        topo_framework: &signer,
        min_voting_threshold: u128,
        required_proposer_stake: u64,
        voting_duration_secs: u64,
    ) {
        system_addresses::assert_aptos_framework(topo_framework);

        voting::register<GovernanceProposal>(topo_framework);
        initialize_partial_voting(topo_framework);
        move_to(topo_framework, GovernanceConfig {
            voting_duration_secs,
            min_voting_threshold,
            required_proposer_stake,
        });
        move_to(topo_framework, GovernanceEvents {
            create_proposal_events: account::new_event_handle<CreateProposalEvent>(topo_framework),
            update_config_events: account::new_event_handle<UpdateConfigEvent>(topo_framework),
            vote_events: account::new_event_handle<VoteEvent>(topo_framework),
        });
        move_to(topo_framework, VotingRecords {
            votes: table::new(),
        });
        move_to(topo_framework, ApprovedExecutionHashes {
            hashes: simple_map::create<u64, vector<u8>>(),
        })
    }

    /// Update the governance configurations. This can only be called as part of resolving a proposal in this same
    /// TopoGovernance.
    public fun update_governance_config(
        topo_framework: &signer,
        min_voting_threshold: u128,
        required_proposer_stake: u64,
        voting_duration_secs: u64,
    ) acquires GovernanceConfig {
        system_addresses::assert_aptos_framework(topo_framework);

        let governance_config = borrow_global_mut<GovernanceConfig>(@topo_framework);
        governance_config.voting_duration_secs = voting_duration_secs;
        governance_config.min_voting_threshold = min_voting_threshold;
        governance_config.required_proposer_stake = required_proposer_stake;
        staking_registry::ensure_min_cooldown_secs(topo_framework, voting_duration_secs);

        event::emit(
            UpdateConfig {
                min_voting_threshold,
                required_proposer_stake,
                voting_duration_secs
            },
        );
    }

    /// Initializes the state for Aptos Governance partial voting. Can only be called through Aptos governance
    /// proposals with a signer for the topo_framework (0x1) account.
    public fun initialize_partial_voting(
        topo_framework: &signer,
    ) {
        system_addresses::assert_aptos_framework(topo_framework);

        move_to(topo_framework, VotingRecordsV2 {
            votes: smart_table::new(),
        });
    }

    #[view]
    public fun get_voting_duration_secs(): u64 acquires GovernanceConfig {
        borrow_global<GovernanceConfig>(@topo_framework).voting_duration_secs
    }

    #[view]
    public fun has_governance_config(): bool {
        exists<GovernanceConfig>(@topo_framework)
    }

    #[view]
    public fun get_min_voting_threshold(): u128 acquires GovernanceConfig {
        borrow_global<GovernanceConfig>(@topo_framework).min_voting_threshold
    }

    #[view]
    public fun get_required_proposer_stake(): u64 acquires GovernanceConfig {
        borrow_global<GovernanceConfig>(@topo_framework).required_proposer_stake
    }

    #[view]
    /// Return true if a stake pool has already voted on a proposal before partial governance voting is enabled.
    public fun has_entirely_voted(voter: address, proposal_id: u64): bool acquires VotingRecords {
        let record_key = RecordKey {
            voter,
            proposal_id,
        };
        // If a stake pool has already voted on a proposal before partial governance voting is enabled,
        // there is a record in VotingRecords.
        let voting_records = borrow_global<VotingRecords>(@topo_framework);
        voting_records.votes.contains(record_key)
    }

    #[view]
    /// Return remaining voting power of a stake pool on a proposal.
    /// Note: a stake pool's voting power on a proposal could increase over time(e.g. rewards/new stake).
    public fun get_remaining_voting_power(
        voter: address,
        proposal_id: u64
    ): u64 acquires VotingRecords, VotingRecordsV2 {
        assert_voting_initialization();

        let proposal_expiration = voting::get_proposal_expiration_secs<GovernanceProposal>(
            @topo_framework,
            proposal_id
        );
        if (is_proposal_expired(proposal_expiration)) {
            return 0
        };
        if (has_entirely_voted(voter, proposal_id)) {
            return 0
        };
        let total_voting_power = staking_registry::get_effective_power(voter);
        if (total_voting_power == 0) {
            return 0
        };
        let record_key = RecordKey {
            voter,
            proposal_id,
        };
        let used_voting_power =
            *VotingRecordsV2[@topo_framework].votes.borrow_with_default(record_key, &0);
        if (used_voting_power >= total_voting_power) {
            0
        } else {
            total_voting_power - used_voting_power
        }
    }

    public fun assert_proposal_expiration(voter: address, proposal_id: u64) {
        assert_voting_initialization();
        let proposal_expiration = voting::get_proposal_expiration_secs<GovernanceProposal>(
            @topo_framework,
            proposal_id
        );
        assert!(
            stake_pool_is_eligible_to_vote(voter, proposal_expiration),
            error::invalid_argument(ENO_VOTING_POWER),
        );
        assert!(
            !is_proposal_expired(proposal_expiration),
            error::invalid_argument(EPROPOSAL_EXPIRED),
        );
    }

    inline fun stake_pool_is_eligible_to_vote(
        stake_pool: address, _proposal_expiration: u64
    ): bool {
        staking_registry::get_effective_power(stake_pool) > 0
    }

    inline fun is_proposal_expired(proposal_expiration: u64): bool {
        // Expiration time is defined as the time since when the proposal is no longer eligible to be voted on.
        timestamp::now_seconds() >= proposal_expiration
    }

    /// Create a single-step proposal with the caller's voting power.
    /// @param execution_hash Required. This is the hash of the resolution script. When the proposal is resolved,
    /// only the exact script with matching hash can be successfully executed.
    public entry fun create_proposal(
        proposer: &signer,
        execution_hash: vector<u8>,
        metadata_location: vector<u8>,
        metadata_hash: vector<u8>,
    ) acquires GovernanceConfig {
        create_proposal_v2(proposer, execution_hash, metadata_location, metadata_hash, false);
    }

    /// Create a single-step or multi-step proposal with the caller's voting power.
    /// @param execution_hash Required. This is the hash of the resolution script. When the proposal is resolved,
    /// only the exact script with matching hash can be successfully executed.
    public entry fun create_proposal_v2(
        proposer: &signer,
        execution_hash: vector<u8>,
        metadata_location: vector<u8>,
        metadata_hash: vector<u8>,
        is_multi_step_proposal: bool,
    ) acquires GovernanceConfig {
        check_governance_permission(proposer);
        let proposer_address = signer::address_of(proposer);

        let governance_config = borrow_global<GovernanceConfig>(@topo_framework);
        let stake_balance = staking_registry::get_effective_power(proposer_address);
        assert!(
            stake_balance >= governance_config.required_proposer_stake,
            error::invalid_argument(EINSUFFICIENT_PROPOSER_STAKE),
        );

        let current_time = timestamp::now_seconds();
        let proposal_expiration = current_time + governance_config.voting_duration_secs;
        assert!(
            stake_pool_is_eligible_to_vote(proposer_address, proposal_expiration),
            error::invalid_argument(ENO_VOTING_POWER),
        );

        let proposal_metadata = create_proposal_metadata(metadata_location, metadata_hash);

        let early_resolution_vote_threshold =
            option::some((stake::get_current_epoch_governance_voting_power() as u128) / 2 + 1);

        let proposal_id = voting::create_proposal_v2(
            proposer_address,
            @topo_framework,
            governance_proposal::create_proposal(),
            execution_hash,
            governance_config.min_voting_threshold,
            proposal_expiration,
            early_resolution_vote_threshold,
            proposal_metadata,
            is_multi_step_proposal,
        );

        event::emit(
            CreateProposal {
                proposal_id,
                proposer: proposer_address,
                execution_hash,
                proposal_metadata,
            },
        );
    }

    /// Vote on proposal with `proposal_id` and all voting power from the caller.
    public entry fun vote(
        voter: &signer,
        proposal_id: u64,
        should_pass: bool,
    ) acquires ApprovedExecutionHashes, VotingRecords, VotingRecordsV2 {
        vote_internal(voter, proposal_id, MAX_U64, should_pass);
    }

    /// Vote on proposal with `proposal_id` and specified voting power from the caller.
    public entry fun partial_vote(
        voter: &signer,
        proposal_id: u64,
        voting_power: u64,
        should_pass: bool,
    ) acquires ApprovedExecutionHashes, VotingRecords, VotingRecordsV2 {
        vote_internal(voter, proposal_id, voting_power, should_pass);
    }

    /// Vote on proposal with `proposal_id` and specified voting_power from the caller.
    /// If voting_power is more than all the left voting power of the caller, use all the left voting power.
    /// If a voter has already voted on a proposal before partial governance voting is enabled, the voter
    /// cannot vote on the proposal even after partial governance voting is enabled.
    fun vote_internal(
        voter: &signer,
        proposal_id: u64,
        voting_power: u64,
        should_pass: bool,
    ) acquires ApprovedExecutionHashes, VotingRecords, VotingRecordsV2 {
        permissioned_signer::assert_master_signer(voter);
        let voter_address = signer::address_of(voter);
        let voting_subject = voter_address;
        assert_proposal_expiration(voting_subject, proposal_id);

        // If a stake pool has already voted on a proposal before partial governance voting is enabled,
        // `get_remaining_voting_power` returns 0.
        let staking_pool_voting_power = get_remaining_voting_power(voting_subject, proposal_id);
        voting_power = min(voting_power, staking_pool_voting_power);

        // Short-circuit if the voter has no voting power.
        assert!(voting_power > 0, error::invalid_argument(ENO_VOTING_POWER));

        voting::vote<GovernanceProposal>(
            &governance_proposal::create_empty_proposal(),
            @topo_framework,
            proposal_id,
            voting_power,
            should_pass,
        );

        let record_key = RecordKey {
            voter: voting_subject,
            proposal_id,
        };
        let used_voting_power = VotingRecordsV2[@topo_framework].votes.borrow_mut_with_default(record_key, 0);
        // This calculation should never overflow because the used voting cannot exceed the total voting power of this stake pool.
        *used_voting_power += voting_power;

        event::emit(
            Vote {
                proposal_id,
                voter: voter_address,
                num_votes: voting_power,
                should_pass,
            },
        );

        let proposal_state = voting::get_proposal_state<GovernanceProposal>(@topo_framework, proposal_id);
        if (proposal_state == PROPOSAL_STATE_SUCCEEDED) {
            add_approved_script_hash(proposal_id);
        }
    }

    public entry fun add_approved_script_hash_script(proposal_id: u64) acquires ApprovedExecutionHashes {
        add_approved_script_hash(proposal_id)
    }

    /// Add the execution script hash of a successful governance proposal to the approved list.
    /// This is needed to bypass the mempool transaction size limit for approved governance proposal transactions that
    /// are too large (e.g. module upgrades).
    public fun add_approved_script_hash(proposal_id: u64) acquires ApprovedExecutionHashes {
        let approved_hashes = borrow_global_mut<ApprovedExecutionHashes>(@topo_framework);

        // Ensure the proposal can be resolved.
        let proposal_state = voting::get_proposal_state<GovernanceProposal>(@topo_framework, proposal_id);
        assert!(proposal_state == PROPOSAL_STATE_SUCCEEDED, error::invalid_argument(EPROPOSAL_NOT_RESOLVABLE_YET));

        let execution_hash = voting::get_execution_hash<GovernanceProposal>(@topo_framework, proposal_id);

        // If this is a multi-step proposal, the proposal id will already exist in the ApprovedExecutionHashes map.
        // We will update execution hash in ApprovedExecutionHashes to be the next_execution_hash.
        if (approved_hashes.hashes.contains_key(&proposal_id)) {
            let current_execution_hash = approved_hashes.hashes.borrow_mut(&proposal_id);
            *current_execution_hash = execution_hash;
        } else {
            approved_hashes.hashes.add(proposal_id, execution_hash);
        }
    }

    /// Resolve a successful single-step proposal. This would fail if the proposal is not successful (not enough votes or more no
    /// than yes).
    public fun resolve(
        proposal_id: u64,
        signer_address: address
    ): signer acquires ApprovedExecutionHashes, GovernanceResponsbility {
        voting::resolve<GovernanceProposal>(@topo_framework, proposal_id);
        remove_approved_hash(proposal_id);
        get_signer(signer_address)
    }

    /// Resolve a successful multi-step proposal. This would fail if the proposal is not successful.
    public fun resolve_multi_step_proposal(
        proposal_id: u64,
        signer_address: address,
        next_execution_hash: vector<u8>
    ): signer acquires GovernanceResponsbility, ApprovedExecutionHashes {
        voting::resolve_proposal_v2<GovernanceProposal>(@topo_framework, proposal_id, next_execution_hash);
        // If the current step is the last step of this multi-step proposal,
        // we will remove the execution hash from the ApprovedExecutionHashes map.
        if (next_execution_hash.length() == 0) {
            remove_approved_hash(proposal_id);
        } else {
            // If the current step is not the last step of this proposal,
            // we replace the current execution hash with the next execution hash
            // in the ApprovedExecutionHashes map.
            add_approved_script_hash(proposal_id)
        };
        get_signer(signer_address)
    }

    /// Remove an approved proposal's execution script hash.
    public fun remove_approved_hash(proposal_id: u64) acquires ApprovedExecutionHashes {
        assert!(
            voting::is_resolved<GovernanceProposal>(@topo_framework, proposal_id),
            error::invalid_argument(EPROPOSAL_NOT_RESOLVED_YET),
        );

        let approved_hashes = &mut borrow_global_mut<ApprovedExecutionHashes>(@topo_framework).hashes;
        if (approved_hashes.contains_key(&proposal_id)) {
            approved_hashes.remove(&proposal_id);
        };
    }

    /// Manually reconfigure. Called at the end of a governance txn that alters on-chain configs.
    ///
    /// WARNING: this function always ensures a reconfiguration starts, but when the reconfiguration finishes depends.
    /// - If feature `RECONFIGURE_WITH_DKG` is disabled, it finishes immediately.
    ///   - At the end of the calling transaction, we will be in a new epoch.
    /// - If feature `RECONFIGURE_WITH_DKG` is enabled, it starts DKG, and the new epoch will start in a block prologue after DKG finishes.
    ///
    /// This behavior affects when an update of an on-chain config (e.g. `ConsensusConfig`, `Features`) takes effect,
    /// since such updates are applied whenever we enter an new epoch.
    public entry fun reconfigure(topo_framework: &signer) {
        system_addresses::assert_aptos_framework(topo_framework);
        if (consensus_config::validator_txn_enabled() && randomness_config::enabled()) {
            if (chunky_dkg_config::enabled()) {
                reconfiguration_with_dkg::try_start_with_chunky_dkg();
            } else {
                reconfiguration_with_dkg::try_start();
            }
        } else {
            reconfiguration_with_dkg::finish(topo_framework);
        }
    }

    /// Change epoch immediately.
    /// If `RECONFIGURE_WITH_DKG` is enabled and we are in the middle of a DKG,
    /// stop waiting for DKG and enter the new epoch without randomness.
    ///
    /// WARNING: currently only used by tests. In most cases you should use `reconfigure()` instead.
    /// TODO: migrate these tests to be aware of async reconfiguration.
    public entry fun force_end_epoch(topo_framework: &signer) {
        system_addresses::assert_aptos_framework(topo_framework);
        reconfiguration_with_dkg::finish(topo_framework);
    }

    /// `force_end_epoch()` equivalent but only called in testnet,
    /// where the core resources account exists and has been granted power to mint Aptos coins.
    public entry fun force_end_epoch_test_only(topo_framework: &signer) acquires GovernanceResponsbility {
        let core_signer = get_signer_testnet_only(topo_framework, @0x1);
        system_addresses::assert_aptos_framework(&core_signer);
        reconfiguration_with_dkg::finish(&core_signer);
    }

    /// Test-only wrapper that lets `@core_resources` shorten the power period
    /// without compiling an auxiliary Move script in smoke tests.
    public entry fun set_power_period_in_epochs_test_only(
        core_resources: &signer,
        power_period_in_epochs: u64,
    ) acquires GovernanceResponsbility {
        let framework_signer = get_signer_testnet_only(core_resources, @0x1);
        poc_power_store::set_power_period_in_epochs(&framework_signer, power_period_in_epochs);
    }

    /// Test-only wrapper that stages a single user power update for the next
    /// period using the framework signer delegated to `@core_resources`.
    public entry fun stage_power_update_test_only(
        core_resources: &signer,
        user: address,
        power: u64,
    ) acquires GovernanceResponsbility {
        let framework_signer = get_signer_testnet_only(core_resources, @0x1);
        let target_period = poc_power_store::get_current_period() + 1;
        poc_power_store::stage_batch_update(
            &framework_signer,
            target_period,
            vector[user],
            vector[power],
        );
    }

    /// Update feature flags and also trigger reconfiguration.
    public fun toggle_features(topo_framework: &signer, enable: vector<u64>, disable: vector<u64>) {
        system_addresses::assert_aptos_framework(topo_framework);
        features::change_feature_flags_for_next_epoch(topo_framework, enable, disable);
        reconfigure(topo_framework);
    }

    /// Only called in testnet where the core resources account exists and has been granted power to mint Aptos coins.
    public fun get_signer_testnet_only(
        core_resources: &signer, signer_address: address): signer acquires GovernanceResponsbility {
        system_addresses::assert_core_resource(core_resources);
        // Core resources account only has mint capability in tests/testnets.
        assert!(topo_coin::has_mint_capability(core_resources), error::unauthenticated(EUNAUTHORIZED));
        get_signer(signer_address)
    }

    /// Return a signer for making changes to 0x1 as part of on-chain governance proposal process.
    fun get_signer(signer_address: address): signer acquires GovernanceResponsbility {
        let governance_responsibility = borrow_global<GovernanceResponsbility>(@topo_framework);
        let signer_cap = governance_responsibility.signer_caps.borrow(&signer_address);
        create_signer_with_capability(signer_cap)
    }

    fun create_proposal_metadata(
        metadata_location: vector<u8>,
        metadata_hash: vector<u8>
    ): SimpleMap<String, vector<u8>> {
        assert!(utf8(metadata_location).length() <= 256, error::invalid_argument(EMETADATA_LOCATION_TOO_LONG));
        assert!(utf8(metadata_hash).length() <= 256, error::invalid_argument(EMETADATA_HASH_TOO_LONG));

        let metadata = simple_map::create<String, vector<u8>>();
        metadata.add(utf8(METADATA_LOCATION_KEY), metadata_location);
        metadata.add(utf8(METADATA_HASH_KEY), metadata_hash);
        metadata
    }

    fun assert_voting_initialization() {
        assert!(exists<VotingRecordsV2>(@topo_framework), error::invalid_state(EPARTIAL_VOTING_NOT_INITIALIZED));
    }

    #[test_only]
    fun create_proposal_for_test(
        proposer: &signer,
        multi_step: bool,
    ) acquires GovernanceConfig {
        let execution_hash = vector[1];
        if (multi_step) {
            create_proposal_v2(
                proposer,
                execution_hash,
                b"",
                b"",
                true,
            );
        } else {
            create_proposal(
                proposer,
                execution_hash,
                b"",
                b"",
            );
        };
    }

    #[test_only]
    fun test_resolving_proposal_generic(
        topo_framework: signer,
        use_generic_resolve_function: bool,
        execution_hash: vector<u8>,
    ) acquires ApprovedExecutionHashes, GovernanceResponsbility {
        // Once expiration time has passed, the proposal should be considered resolve now as there are more yes votes
        // than no.
        timestamp::update_global_time_for_test(100001000000);
        let proposal_state = voting::get_proposal_state<GovernanceProposal>(signer::address_of(&topo_framework), 0);
        assert!(proposal_state == PROPOSAL_STATE_SUCCEEDED, proposal_state);

        // Add approved script hash.
        add_approved_script_hash(0);
        let approved_hashes = borrow_global<ApprovedExecutionHashes>(@topo_framework).hashes;
        assert!(*approved_hashes.borrow(&0) == execution_hash, 0);

        // Resolve the proposal.
        let account =
            if (use_generic_resolve_function) {
                resolve_multi_step_proposal(0, @topo_framework, vector::empty<u8>())
            } else {
                resolve(0, @topo_framework)
            };
        assert!(signer::address_of(&account) == @topo_framework, 1);
        assert!(voting::is_resolved<GovernanceProposal>(@topo_framework, 0), 2);
        let approved_hashes = borrow_global<ApprovedExecutionHashes>(@topo_framework).hashes;
        assert!(!approved_hashes.contains_key(&0), 3);
    }

    #[test(topo_framework = @topo_framework, proposer = @0x123, yes_voter = @0x234, no_voter = @345)]
    public entry fun test_voting(
        topo_framework: signer,
        proposer: signer,
        yes_voter: signer,
        no_voter: signer,
    ) acquires ApprovedExecutionHashes, GovernanceConfig, GovernanceResponsbility, VotingRecords, VotingRecordsV2 {
        setup_voting_with_initialized_stake(&topo_framework, &proposer, &yes_voter, &no_voter);
        let execution_hash = vector[1];
        create_proposal_for_test(&proposer, false);
        vote(&yes_voter, 0, true);
        vote(&no_voter, 0, false);
        test_resolving_proposal_generic(topo_framework, false, execution_hash);
    }

    #[test(topo_framework = @topo_framework, proposer = @0x123, yes_voter = @0x234, no_voter = @345)]
    public entry fun test_voting_multi_step(
        topo_framework: signer,
        proposer: signer,
        yes_voter: signer,
        no_voter: signer,
    ) acquires ApprovedExecutionHashes, GovernanceConfig, GovernanceResponsbility, VotingRecords, VotingRecordsV2 {
        setup_voting_with_initialized_stake(&topo_framework, &proposer, &yes_voter, &no_voter);
        let execution_hash = vector[1];
        create_proposal_for_test(&proposer, true);
        vote(&yes_voter, 0, true);
        vote(&no_voter, 0, false);
        test_resolving_proposal_generic(topo_framework, true, execution_hash);
    }

    #[test(topo_framework = @topo_framework, proposer = @0x123, yes_voter = @0x234, no_voter = @345)]
    #[expected_failure(abort_code = 0x5000a, location = topo_framework::voting)]
    public entry fun test_voting_multi_step_cannot_use_single_step_resolve(
        topo_framework: signer,
        proposer: signer,
        yes_voter: signer,
        no_voter: signer,
    ) acquires ApprovedExecutionHashes, GovernanceConfig, GovernanceResponsbility, VotingRecords, VotingRecordsV2 {
        setup_voting_with_initialized_stake(&topo_framework, &proposer, &yes_voter, &no_voter);
        let execution_hash = vector[1];
        create_proposal_for_test(&proposer, true);
        vote(&yes_voter, 0, true);
        vote(&no_voter, 0, false);
        test_resolving_proposal_generic(topo_framework, false, execution_hash);
    }

    #[test(topo_framework = @topo_framework, proposer = @0x123, voter_1 = @0x234, voter_2 = @345)]
    public entry fun test_stake_pool_can_vote_only_with_its_own_voting_power(
        topo_framework: signer,
        proposer: signer,
        voter_1: signer,
        voter_2: signer,
    ) acquires ApprovedExecutionHashes, GovernanceConfig, GovernanceResponsbility, VotingRecords, VotingRecordsV2 {
        setup_voting_with_initialized_stake(&topo_framework, &proposer, &voter_1, &voter_2);
        let execution_hash = vector[1];
        let proposer_addr = signer::address_of(&proposer);
        let voter_1_addr = signer::address_of(&voter_1);
        let voter_2_addr = signer::address_of(&voter_2);

        create_proposal_for_test(&proposer, true);

        partial_vote(&voter_1, 0, 9, true);
        // The total voting power of voter_1 is 20. It can only vote with 20 voting power even we pass 30 as the argument.
        partial_vote(&voter_1, 0, 30, true);

        assert!(get_remaining_voting_power(proposer_addr, 0) == 100, 0);
        assert!(get_remaining_voting_power(voter_1_addr, 0) == 0, 1);
        assert!(get_remaining_voting_power(voter_2_addr, 0) == 10, 2);

        test_resolving_proposal_generic(topo_framework, true, execution_hash);
    }

    #[test_only]
    fun setup_voting_with_initialized_stake(
        topo_framework: &signer,
        proposer: &signer,
        yes_voter: &signer,
        no_voter: &signer,
    ) acquires GovernanceResponsbility {
        use topo_framework::account;

        timestamp::set_time_has_started_for_testing(topo_framework);
        account::create_account_for_test(signer::address_of(topo_framework));
        account::create_account_for_test(signer::address_of(proposer));
        account::create_account_for_test(signer::address_of(yes_voter));
        account::create_account_for_test(signer::address_of(no_voter));

        // Initialize the governance.
        stake::initialize_for_test_custom(topo_framework, 0, 1000, 2000, true, 0, 1, 1000);
        initialize(topo_framework, 10, 100, 1000);
        store_signer_cap(
            topo_framework,
            @topo_framework,
            account::create_test_signer_cap(@topo_framework),
        );

        let (_sk_1, pk_1, pop_1) = stake::generate_identity();
        let (_sk_2, pk_2, pop_2) = stake::generate_identity();
        let (_sk_3, pk_3, pop_3) = stake::generate_identity();
        stake::initialize_test_validator(topo_framework, &pk_1, &pop_1, proposer, 100, true, false);
        stake::initialize_test_validator(topo_framework, &pk_2, &pop_2, yes_voter, 20, true, false);
        stake::initialize_test_validator(topo_framework, &pk_3, &pop_3, no_voter, 10, true, false);
        stake::end_epoch();
    }

    #[test(topo_framework = @topo_framework, proposer = @0x123, yes_voter = @0x234, no_voter = @345)]
    public entry fun test_replace_execution_hash(
        topo_framework: signer,
        proposer: signer,
        yes_voter: signer,
        no_voter: signer,
    ) acquires GovernanceResponsbility, GovernanceConfig, ApprovedExecutionHashes, VotingRecords, VotingRecordsV2 {
        setup_voting_with_initialized_stake(&topo_framework, &proposer, &yes_voter, &no_voter);

        create_proposal_for_test(&proposer, true);
        vote(&yes_voter, 0, true);
        vote(&no_voter, 0, false);

        // Add approved script hash.
        timestamp::update_global_time_for_test(100001000000);
        add_approved_script_hash(0);

        // Resolve the proposal.
        let execution_hash = vector::empty<u8>();
        let next_execution_hash = vector::empty<u8>();
        execution_hash.push_back(1);
        next_execution_hash.push_back(10);

        voting::resolve_proposal_v2<GovernanceProposal>(@topo_framework, 0, next_execution_hash);

        if (next_execution_hash.length() == 0) {
            remove_approved_hash(0);
        } else {
            add_approved_script_hash(0)
        };

        let approved_hashes = borrow_global<ApprovedExecutionHashes>(@topo_framework).hashes;
        assert!(*approved_hashes.borrow(&0) == vector[10u8, ], 1);
    }

    #[test(
        topo_framework = @topo_framework,
        proposer = @0x123,
        yes_voter = @0x234,
        no_voter = @0x345,
        delegator = @0x456
    )]
    public entry fun test_update_governance_config_raises_cooldown_floor(
        topo_framework: signer,
        proposer: signer,
        yes_voter: signer,
        no_voter: signer,
        delegator: signer,
    ) acquires GovernanceResponsbility, GovernanceConfig {
        let _unused_delegator = delegator;

        setup_voting_with_initialized_stake(&topo_framework, &proposer, &yes_voter, &no_voter);

        update_governance_config(&topo_framework, 10, 100, 5000);
        assert!(staking_registry::get_cooldown_secs() == 5000, 0);

        staking_config::update_recurring_lockup_duration_secs(&topo_framework, 6000);
        staking_registry::ensure_min_cooldown_secs(&topo_framework, 6000);
        assert!(staking_registry::get_cooldown_secs() == 6000, 1);

        update_governance_config(&topo_framework, 10, 100, 3000);
        assert!(staking_registry::get_cooldown_secs() == 6000, 2);
    }

    #[test(
        topo_framework = @topo_framework,
        proposer = @0x123,
        yes_voter = @0x234,
        no_voter = @0x345,
        delegator = @0x456
    )]
    public entry fun test_create_proposal_uses_live_total_voting_power(
        topo_framework: signer,
        proposer: signer,
        yes_voter: signer,
        no_voter: signer,
        delegator: signer,
    ) acquires GovernanceResponsbility, GovernanceConfig {
        setup_voting_with_initialized_stake(&topo_framework, &proposer, &yes_voter, &no_voter);

        let proposer_address = signer::address_of(&proposer);
        let delegator_address = signer::address_of(&delegator);
        topo_framework::account::create_account_for_test(delegator_address);
        let target_period = topo_framework::poc_power_store::get_current_period() + 1;
        topo_framework::poc_power_store::stage_batch_update(
            &topo_framework,
            target_period,
            vector[delegator_address],
            vector[40u64],
        );
        stake::mint_and_add_stake(&delegator, 40);
        while (topo_framework::poc_power_store::get_current_period() < target_period) {
            stake::end_epoch();
        };
        staking_registry::delegate(&delegator, proposer_address);

        let stale_total = staking_registry::get_total_staked_power();
        let live_total = stake::get_current_epoch_governance_voting_power();
        assert!(live_total > stale_total, 0);

        update_governance_config(&topo_framework, 10, 1, 1000);
        create_proposal_for_test(&proposer, true);
        let threshold =
            voting::get_early_resolution_vote_threshold<GovernanceProposal>(@topo_framework, 0);
        assert!(threshold.is_some(), 1);
        assert!(*threshold.borrow() == (live_total as u128) / 2 + 1, 2);
    }

    #[verify_only]
    public fun initialize_for_verification(
        topo_framework: &signer,
        min_voting_threshold: u128,
        required_proposer_stake: u64,
        voting_duration_secs: u64,
    ) {
        initialize(topo_framework, min_voting_threshold, required_proposer_stake, voting_duration_secs);
    }
}
